# Generated by Django 5.1.1 on 2024-09-05 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoptions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoption',
            name='updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoptions_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animal',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animal',
            name='updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladoption',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladoption',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanimal',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanimal',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
