# Generated by Django 5.1.1 on 2024-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_created_at_customuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('volunteer', 'Volunteer'), ('adopter', 'Adopter')], default='adopter', max_length=10),
        ),
    ]
